# Site settings
title: MySpace
email: yangkl16@mails.tsinghua.edu.cn
baseurl: "https://github.com/Youngkl0726" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: 理想主义的文艺程序猿

# Social icons
facebook: yklguge
linkedin: 杨昆霖
github: Youngkl0726
#deviantart: username
#codepen: username

footer: © Young

# Build settings
markdown: kramdown
